### ISSUE TITLE
support more formats

### ISSUE THREAD

**Issue by aeosynth** [lob/calipers#21]
i'm personally interested in gifs

**Comment by mgartner** [comment]
Looking at the GIF spec, it looks fairly straight forward. I'll work on adding it today.

**Comment by aeosynth** [comment]
cool. btw, what's the reason for not just using `image-size`?

**Comment by mgartner** [comment]
`image-size` works great for images. We had the need to also measure PDFs, which is why we created Calipers. To accomadate for PDFs, the `image-size` library API would need to change significantly and the Poppler dependency would be added, which might not be ideal for some. That's why we created a separate module instead of adding on to image-size.
